// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\atmosphere_glsl[3886] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "#ifdef GL_ES\n"
    "precision mediump float;\n"
    "#endif\n"
    "\n"
    "uniform highp float u_atm_p[12];\n"
    "uniform highp vec3  u_sun;\n"
    "uniform highp float u_tm[3]; // Tonemapping koefs.\n"
    "\n"
    "varying lowp    vec4        v_color;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#includes \"projections.glsl\"\n"
    "\n"
    "attribute highp   vec4       a_pos;\n"
    "attribute highp   vec3       a_sky_pos;\n"
    "attribute highp   float      a_luminance;\n"
    "\n"
    "highp float gammaf(highp float c)\n"
    "{\n"
    "    if (c < 0.0031308)\n"
    "      return 19.92 * c;\n"
    "    return 1.055 * pow(c, 1.0 / 2.4) - 0.055;\n"
    "}\n"
    "\n"
    "vec3 xyy_to_srgb(highp vec3 xyy)\n"
    "{\n"
    "    const highp mat3 xyz_to_rgb = mat3(3.2406, -0.9689, 0.0557,\n"
    "                                      -1.5372, 1.8758, -0.2040,\n"
    "                                      -0.4986, 0.0415, 1.0570);\n"
    "    highp vec3 xyz = vec3(xyy[0] * xyy[2] / xyy[1], xyy[2],\n"
    "               (1.0 - xyy[0] - xyy[1]) * xyy[2] / xyy[1]);\n"
    "    highp vec3 srgb = xyz_to_rgb * xyz;\n"
    "    clamp(srgb, 0.0, 1.0);\n"
    "    return srgb;\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    highp vec3 xyy;\n"
    "    highp float cos_gamma, cos_gamma2, gamma, cos_theta;\n"
    "    highp vec3 p = a_sky_pos;\n"
    "\n"
    "    gl_Position = proj(a_pos.xyz);\n"
    "\n"
    "    // First compute the xy color component (chromaticity) from Preetham model\n"
    "    // and re-inject a_luminance for Y component (luminance).\n"
    "    p[2] = abs(p[2]); // Mirror below horizon.\n"
    "    cos_gamma = dot(p, u_sun);\n"
    "    cos_gamma2 = cos_gamma * cos_gamma;\n"
    "    gamma = acos(cos_gamma);\n"
    "    cos_theta = p[2];\n"
    "\n"
    "    xyy.x = ((1. + u_atm_p[0] * exp(u_atm_p[1] / cos_theta)) *\n"
    "             (1. + u_atm_p[2] * exp(u_atm_p[3] * gamma) +\n"
    "              u_atm_p[4] * cos_gamma2)) * u_atm_p[5];\n"
    "    xyy.y = ((1. + u_atm_p[6] * exp(u_atm_p[7] / cos_theta)) *\n"
    "             (1. + u_atm_p[8] * exp(u_atm_p[9] * gamma) +\n"
    "              u_atm_p[10] * cos_gamma2)) * u_atm_p[11];\n"
    "    xyy.z = a_luminance;\n"
    "\n"
    "    // Ad-hoc tuning. Scaling before the blue shift allows to obtain proper\n"
    "    // blueish colors at sun set instead of very red, which is a shortcoming\n"
    "    // of preetham model.\n"
    "    xyy.z *= 0.08;\n"
    "\n"
    "    // Convert this sky luminance/chromaticity into perceived color using model\n"
    "    // from Henrik Wann Jensen (2000)\n"
    "    // We deal with 3 cases:\n"
    "    //  * Y <= 0.01: scotopic vision. Only the eyes' rods see. No colors,\n"
    "    //    everything is converted to night blue (xy = 0.25, 0.25)\n"
    "    //  * Y > 3.981: photopic vision. Only the eyes's cones seew ith full colors\n"
    "    //  * Y > 0.01 and Y <= 3.981: mesopic vision. Rods and cones see in a\n"
    "    //    transition state.\n"
    "    //\n"
    "    // Compute s, ratio between scotopic and photopic vision\n"
    "    highp float op = (log(xyy.z) / log(10.) + 2.) / 2.6;\n"
    "    highp float s = (xyy.z <= 0.01) ? 0.0 : (xyy.z > 3.981) ? 1.0 : op * op * (3. - 2. * op);\n"
    "\n"
    "    // Perform the blue shift on chromaticity\n"
    "    xyy.x = mix(0.25, xyy.x, s);\n"
    "    xyy.y = mix(0.25, xyy.y, s);\n"
    "    // Scale scotopic luminance for scotopic pixels\n"
    "    xyy.z = 0.4468 * (1. - s) * xyy.z + s * xyy.z;\n"
    "\n"
    "    // Apply logarithmic tonemapping on luminance Y only.\n"
    "    // There is a difference with the code in tonemapper.c (assuming q == 1)\n"
    "    // because we cap the exposure to 1 to avoid saturating the sky.\n"
    "    // This is ad-hoc code to fix rendering issue.\n"
    "    xyy.z = min(0.7, log(1.0 + xyy.z * u_tm[0]) / log(1.0 + u_tm[1] * u_tm[0]) * u_tm[2]);\n"
    "\n"
    "    // Convert xyY to sRGB\n"
    "    highp vec3 rgb = xyy_to_srgb(xyy);\n"
    "\n"
    "    // Apply gamma correction\n"
    "    v_color = vec4(gammaf(rgb.r), gammaf(rgb.g),gammaf(rgb.b), 1.0);\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_FragColor = v_color;\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\atmosphere_glsl, "shaders\atmosphere.glsl", DATA_shaders\atmosphere_glsl, false)

