// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\blit_glsl[1032] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "uniform mediump vec4        u_color;\n"
    "uniform mediump sampler2D   u_tex;\n"
    "\n"
    "varying highp   vec2        v_tex_pos;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#ifdef PROJ\n"
    "#includes \"projections.glsl\"\n"
    "#endif\n"
    "\n"
    "attribute highp     vec3    a_pos;\n"
    "attribute mediump   vec2    a_tex_pos;\n"
    "\n"
    "void main()\n"
    "{\n"
    "#ifdef PROJ\n"
    "    gl_Position = proj(a_pos);\n"
    "#else\n"
    "    gl_Position = vec4(a_pos, 1.0);\n"
    "#endif\n"
    "    v_tex_pos = a_tex_pos;\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "#ifndef TEXTURE_LUMINANCE\n"
    "    gl_FragColor = texture2D(u_tex, v_tex_pos) * u_color;\n"
    "#else\n"
    "    // Luminance mode: the texture only applies to the alpha channel.\n"
    "    gl_FragColor = u_color;\n"
    "    gl_FragColor.a *= texture2D(u_tex, v_tex_pos).r;\n"
    "#endif\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\blit_glsl, "shaders\blit.glsl", DATA_shaders\blit_glsl, false)

