// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\fog_glsl[898] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "#ifdef GL_ES\n"
    "precision mediump float;\n"
    "#endif\n"
    "\n"
    "uniform lowp    vec4        u_color;\n"
    "\n"
    "varying lowp    vec4        v_color;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#includes \"projections.glsl\"\n"
    "\n"
    "attribute highp   vec4       a_pos;\n"
    "attribute highp   vec3       a_sky_pos;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = proj(a_pos.xyz);\n"
    "    const lowp float height = 0.2;\n"
    "    const lowp float alpha = 0.15;\n"
    "    lowp float d = smoothstep(height, 0.0, abs(a_sky_pos.z));\n"
    "    v_color = u_color;\n"
    "    v_color.a *= alpha * d;\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_FragColor = v_color;\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\fog_glsl, "shaders\fog.glsl", DATA_shaders\fog_glsl, false)

