// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\lines_glsl[2193] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "uniform   lowp      vec2    u_win_size;\n"
    "uniform   lowp      float   u_line_width;\n"
    "uniform   lowp      float   u_line_glow;\n"
    "uniform   lowp      vec4    u_color;\n"
    "\n"
    "#ifdef DASH\n"
    "// Dash effect defined as a total length (dash and space, in uv unit),\n"
    "// and the ratio of the dash dot to the length.\n"
    "uniform   lowp      float   u_dash_length;\n"
    "uniform   lowp      float   u_dash_ratio;\n"
    "#endif\n"
    "\n"
    "#ifdef FADE\n"
    "uniform     lowp    float   u_fade_dist_min;\n"
    "uniform     lowp    float   u_fade_dist_max;\n"
    "varying     lowp    float   v_alpha;\n"
    "#endif\n"
    "\n"
    "varying   mediump   vec2    v_uv;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#includes \"projections.glsl\"\n"
    "\n"
    "attribute highp     vec3    a_pos;\n"
    "attribute highp     vec2    a_wpos;\n"
    "attribute highp     vec2    a_tex_pos;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = proj(a_pos);\n"
    "    gl_Position.xy = (a_wpos / u_win_size - 0.5) * vec2(2.0, -2.0);\n"
    "    gl_Position.xy *= gl_Position.w;\n"
    "    v_uv = a_tex_pos;\n"
    "\n"
    "#ifdef FADE\n"
    "    v_alpha = smoothstep(u_fade_dist_max, u_fade_dist_min, -a_pos.z);\n"
    "#endif\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mediump float dist = abs(v_uv.y); // Distance to line in pixel.\n"
    "    // Use smooth step on 2.4px to emulate an anti-aliased line\n"
    "    mediump float base = smoothstep(u_line_width / 2.0 + 1.2, u_line_width / 2.0 - 1.2, dist);\n"
    "    // Generate a glow with 5px radius\n"
    "    mediump float glow = (1.0 - dist / 5.0) * u_line_glow;\n"
    "    // Only use the most visible of both to avoid changing brightness\n"
    "    gl_FragColor = vec4(u_color.rgb, u_color.a * max(glow, base));\n"
    "\n"
    "#ifdef DASH\n"
    "    lowp float len = u_dash_length;\n"
    "    lowp float r = u_dash_ratio;\n"
    "    gl_FragColor.a *= smoothstep(len / 2.0 * r + 0.01,\n"
    "                                 len / 2.0 * r - 0.01,\n"
    "                                 abs(mod(v_uv.x, len) - len / 2.0));\n"
    "#endif\n"
    "\n"
    "#ifdef FADE\n"
    "    gl_FragColor.a *= v_alpha;\n"
    "#endif\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\lines_glsl, "shaders\lines.glsl", DATA_shaders\lines_glsl, false)

