// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\planet_glsl[7474] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "#define PI 3.14159265\n"
    "\n"
    "#ifdef GL_ES\n"
    "precision mediump float;\n"
    "#endif\n"
    "\n"
    "uniform lowp    vec4      u_color;\n"
    "uniform mediump sampler2D u_tex;\n"
    "uniform mediump sampler2D u_normal_tex;\n"
    "uniform mediump mat3      u_tex_transf;\n"
    "uniform mediump mat3      u_normal_tex_transf;\n"
    "uniform lowp    vec3      u_light_emit;\n"
    "uniform lowp    float     u_min_brightness;\n"
    "uniform mediump mat4      u_mv;  // Model view matrix.\n"
    "uniform lowp    int       u_has_normal_tex;\n"
    "uniform lowp    int       u_material; // 0: Oren Nayar, 1: generic, 2: ring\n"
    "uniform lowp    int       u_is_moon; // Set to 1 for the Moon only.\n"
    "uniform lowp    float     u_contrast;\n"
    "\n"
    "uniform highp   vec4      u_sun; // Sun pos (xyz) and radius (w).\n"
    "\n"
    "#ifdef HAS_SHADOW\n"
    "// Up to four spheres for illumination ray tracing.\n"
    "uniform mediump sampler2D u_shadow_color_tex; // Used for the Moon.\n"
    "uniform lowp    int       u_shadow_spheres_nb;\n"
    "uniform highp   mat4      u_shadow_spheres;\n"
    "#endif\n"
    "\n"
    "varying highp   vec3 v_mpos;\n"
    "varying mediump vec2 v_tex_pos;\n"
    "varying mediump vec2 v_normal_tex_pos;\n"
    "varying lowp    vec4 v_color;\n"
    "varying highp   vec3 v_normal;\n"
    "varying highp   vec3 v_tangent;\n"
    "varying highp   vec3 v_bitangent;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#includes \"projections.glsl\"\n"
    "\n"
    "attribute highp   vec3 a_pos;     // View position (with fake scaling).\n"
    "attribute highp   vec3 a_mpos;    // Model position (without fake scaling).\n"
    "attribute mediump vec2 a_tex_pos;\n"
    "attribute lowp    vec3 a_color;\n"
    "attribute highp   vec3 a_normal;\n"
    "attribute highp   vec3 a_tangent;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = proj(a_pos);\n"
    "\n"
    "    v_mpos = a_mpos;\n"
    "    v_tex_pos = (u_tex_transf * vec3(a_tex_pos, 1.0)).xy;\n"
    "    v_normal_tex_pos = (u_normal_tex_transf * vec3(a_tex_pos, 1.0)).xy;\n"
    "    v_color = vec4(a_color, 1.0) * u_color;\n"
    "\n"
    "    v_normal = normalize(a_normal);\n"
    "    v_tangent = normalize(a_tangent);\n"
    "    v_bitangent = normalize(cross(v_normal, v_tangent));\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "float oren_nayar_diffuse(\n"
    "        vec3 lightDirection,\n"
    "        vec3 viewDirection,\n"
    "        vec3 surfaceNormal,\n"
    "        float roughness,\n"
    "        float albedo) {\n"
    "\n"
    "    float r2 = roughness * roughness;\n"
    "    float LdotV = dot(lightDirection, viewDirection);\n"
    "    float NdotL = dot(lightDirection, surfaceNormal);\n"
    "    float NdotV = dot(surfaceNormal, viewDirection);\n"
    "    float NaL = acos(NdotL);\n"
    "    float NaV = acos(NdotV);\n"
    "    float alpha = max(NaV, NaL);\n"
    "    float beta = min(NaV, NaL);\n"
    "    float gamma = dot(viewDirection - surfaceNormal * NdotV,\n"
    "                      lightDirection - surfaceNormal * NdotL);\n"
    "    float A = 1.0 - 0.5 * (r2 / (r2 + 0.33));\n"
    "    float B = 0.45 * r2 / (r2 + 0.09);\n"
    "    float C = sin(alpha) * tan(beta);\n"
    "    float scale = 1.6; // Empirical value!\n"
    "    return max(0.0, NdotL) * (A + B * max(0.0, gamma) * C) * scale;\n"
    "}\n"
    "\n"
    "/*\n"
    " * Compute the illumination if we only consider a single sphere in the scene.\n"
    " * Parameters:\n"
    " *   p       - The surface point where we compute the illumination.\n"
    " *   sphere  - A sphere: xyz -> pos, w -> radius.\n"
    " *   sun_pos - Position of the sun.\n"
    " *   sun_r   - Precomputed sun angular radius from the given point.\n"
    " */\n"
    "float illumination_sphere(highp vec3 p, highp vec4 sphere,\n"
    "                          highp vec3 sun_pos, highp float sun_r)\n"
    "{\n"
    "    // Sphere angular radius as viewed from the point.\n"
    "    highp float sph_r = asin(sphere.w / length(sphere.xyz - p));\n"
    "    // Angle <sun, pos, sphere>\n"
    "    highp float d = acos(min(1.0, dot(normalize(sun_pos - p),\n"
    "                                normalize(sphere.xyz - p))));\n"
    "\n"
    "    // Special case for the moon, to simulate lunar eclipses.\n"
    "    // We assume the only body that can cast shadow on the moon is the Earth.\n"
    "    if (u_is_moon == 1) {\n"
    "        if (d >= sun_r + sph_r) return 1.0; // Outside of shadow.\n"
    "        if (d <= sph_r - sun_r) return d / (sph_r - sun_r) * 0.6; // Umbra.\n"
    "        if (d <= sun_r - sph_r) // Penumbra completely inside.\n"
    "            return 1.0 - sph_r * sph_r / (sun_r * sun_r);\n"
    "        return ((d - abs(sun_r - sph_r)) /\n"
    "                (sun_r + sph_r - abs(sun_r - sph_r))) * 0.4 + 0.6;\n"
    "    }\n"
    "\n"
    "    if (d >= sun_r + sph_r) return 1.0; // Outside of shadow.\n"
    "    if (d <= sph_r - sun_r) return 0.0; // Umbra.\n"
    "    if (d <= sun_r - sph_r) // Penumbra completely inside.\n"
    "        return 1.0 - sph_r * sph_r / (sun_r * sun_r);\n"
    "\n"
    "    // Penumbra partially inside.\n"
    "    // I took this from Stellarium, even though I am not sure how it works.\n"
    "    highp float x = (sun_r * sun_r + d * d - sph_r * sph_r) / (2.0 * d);\n"
    "    highp float alpha = acos(x / sun_r);\n"
    "    highp float beta = acos((d - x) / sph_r);\n"
    "    highp float AR = sun_r * sun_r * (alpha - 0.5 * sin(2.0 * alpha));\n"
    "    highp float Ar = sph_r * sph_r * (beta - 0.5 * sin(2.0 * beta));\n"
    "    highp float AS = sun_r * sun_r * 2.0 * 1.57079633;\n"
    "    return 1.0 - (AR + Ar) / AS;\n"
    "}\n"
    "\n"
    "/*\n"
    " * Compute the illumination at a given point.\n"
    " * Parameters:\n"
    " *   p       - The surface point where we compute the illumination.\n"
    " */\n"
    "float illumination(highp vec3 p)\n"
    "{\n"
    "#ifndef HAS_SHADOW\n"
    "    return 1.0;\n"
    "#else\n"
    "    if (u_shadow_spheres_nb == 0) return 1.0;\n"
    "    mediump float ret = 1.0;\n"
    "    highp float sun_r = asin(u_sun.w / length(u_sun.xyz - p));\n"
    "    for (int i = 0; i < 4; ++i) {\n"
    "        if (u_shadow_spheres_nb > i) {\n"
    "            highp vec4 sphere = u_shadow_spheres[i];\n"
    "            ret = min(ret, illumination_sphere(p, sphere, u_sun.xyz, sun_r));\n"
    "        }\n"
    "    }\n"
    "    return ret;\n"
    "#endif\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 light_dir = normalize(u_sun.xyz - v_mpos);\n"
    "    // Compute N in view space\n"
    "    vec3 n = v_normal;\n"
    "    if (u_has_normal_tex != 0) {\n"
    "        n = texture2D(u_normal_tex, v_normal_tex_pos).rgb - vec3(0.5, 0.5, 0.0);\n"
    "        // XXX: inverse the Y coordinates, don't know why!\n"
    "        n = +n.x * v_tangent - n.y * v_bitangent + n.z * v_normal;\n"
    "    }\n"
    "    n = normalize(n);\n"
    "    vec4 base_color = texture2D(u_tex, v_tex_pos) * v_color;\n"
    "    vec3 color = (base_color.rgb - 0.5) * u_contrast + 0.5;\n"
    "\n"
    "    if (u_material == 0) { // oren_nayar.\n"
    "        float power = oren_nayar_diffuse(light_dir,\n"
    "                                         normalize(-v_mpos),\n"
    "                                         n,\n"
    "                                         0.9, 0.12);\n"
    "        #ifdef HAS_SHADOW\n"
    "        lowp float illu = illumination(v_mpos);\n"
    "        power *= illu;\n"
    "        #endif\n"
    "\n"
    "        power = max(power, u_min_brightness);\n"
    "        color *= power;\n"
    "\n"
    "        // Earth shadow effect on the moon.\n"
    "        #ifdef HAS_SHADOW\n"
    "        if (u_is_moon == 1 && illu < 0.99) {\n"
    "            vec4 shadow_col = texture2D(u_shadow_color_tex, vec2(illu, 0.5));\n"
    "            color = mix(color, shadow_col.rgb, shadow_col.a);\n"
    "        }\n"
    "        #endif\n"
    "\n"
    "    } else if (u_material == 1) { // basic\n"
    "        float light = max(0.0, dot(n, light_dir));\n"
    "        light = max(light, u_min_brightness);\n"
    "        color *= vec3(light) + u_light_emit;\n"
    "\n"
    "    } else if (u_material == 2) { // ring\n"
    "        lowp float illu = illumination(v_mpos);\n"
    "        illu = max(illu, u_min_brightness);\n"
    "        color *= illu;\n"
    "    }\n"
    "\n"
    "    gl_FragColor = vec4(color, base_color.a);\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\planet_glsl, "shaders\planet.glsl", DATA_shaders\planet_glsl, false)

