// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\points_glsl[1422] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "uniform lowp vec4 u_color;\n"
    "\n"
    "// Size of the core point, not including the halo relative to the total\n"
    "// size of the rendered point.\n"
    "// 0 -> only halo (not supported), 1 -> no halo\n"
    "uniform lowp float u_core_size;\n"
    "\n"
    "varying lowp    vec4 v_color;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "attribute lowp    vec4  a_color;\n"
    "attribute mediump float a_size;\n"
    "\n"
    "#ifdef IS_3D\n"
    "    #include \"projections.glsl\"\n"
    "    attribute highp   vec3  a_pos;\n"
    "#else\n"
    "    attribute highp   vec2  a_pos;\n"
    "#endif\n"
    "\n"
    "void main()\n"
    "{\n"
    "    #ifdef IS_3D\n"
    "        gl_Position = proj(a_pos);\n"
    "    #else\n"
    "        gl_Position = vec4(a_pos, 1.0, 1.0);\n"
    "    #endif\n"
    "\n"
    "    gl_PointSize = a_size * 2.0 / u_core_size;\n"
    "    v_color = a_color * u_color;\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "    mediump float dist;\n"
    "    mediump float k;\n"
    "    dist = 2.0 * distance(gl_PointCoord, vec2(0.5, 0.5));\n"
    "\n"
    "    // Center bright point.\n"
    "    k = smoothstep(u_core_size * 1.25, u_core_size * 0.75, dist);\n"
    "\n"
    "    // Halo\n"
    "    k += smoothstep(1.0, 0.0, dist) * 0.08;\n"
    "    gl_FragColor.rgb = v_color.rgb;\n"
    "    gl_FragColor.a = v_color.a * clamp(k, 0.0, 1.0);\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\points_glsl, "shaders\points.glsl", DATA_shaders\points_glsl, false)

