// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\projections_glsl[1913] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "/*\n"
    " * Helper to perform different non linear projection.\n"
    " *\n"
    " * Define one function: vec4 proj(vec3).\n"
    " *\n"
    " * PROJ should be defined with the id of the projection used.\n"
    " */\n"
    "\n"
    "#define PROJ_PERSPECTIVE        1\n"
    "#define PROJ_STEROGRAPHIC       2\n"
    "#define PROJ_MOLLWEIDE          5\n"
    "\n"
    "#ifndef PROJ\n"
    "#error PROJ undefined\n"
    "#endif\n"
    "\n"
    "uniform highp mat4 u_proj_mat;\n"
    "\n"
    "#if (PROJ == PROJ_PERSPECTIVE)\n"
    "highp vec4 proj(highp vec3 pos) {\n"
    "    return u_proj_mat * vec4(pos, 1.0);\n"
    "}\n"
    "#endif\n"
    "\n"
    "#if (PROJ == PROJ_STEROGRAPHIC)\n"
    "\n"
    "highp vec4 proj(highp vec3 pos) {\n"
    "    highp float dist = length(pos);\n"
    "    highp vec3 p = pos / dist;\n"
    "    p.xy /= 0.5 * (1.0 - p.z);\n"
    "    p.z = -1.0;\n"
    "    p *= dist;\n"
    "    return u_proj_mat * vec4(p, 1.0);\n"
    "}\n"
    "\n"
    "#endif\n"
    "\n"
    "#if (PROJ == PROJ_MOLLWEIDE)\n"
    "\n"
    "#define PI 3.14159265\n"
    "#define MAX_ITER 10\n"
    "#define PRECISION 1e-7\n"
    "#define SQRT2 1.4142135623730951\n"
    "\n"
    "highp vec4 proj(highp vec3 v)\n"
    "{\n"
    "    highp float dist = length(v);\n"
    "    highp float phi, lambda, theta, d, k;\n"
    "\n"
    "    lambda = atan(v[0], -v[2]);\n"
    "    phi = atan(v[1], sqrt(v[0] * v[0] + v[2] * v[2]));\n"
    "\n"
    "    k = PI * sin(phi);\n"
    "    theta = phi;\n"
    "    for (int i = 0; i < MAX_ITER; i++) {\n"
    "        d = 2.0 + 2.0 * cos(2.0 * theta);\n"
    "        if (abs(d) < PRECISION) break;\n"
    "        d = (2.0 * theta + sin(2.0 * theta) - k) / d;\n"
    "        theta -= d;\n"
    "        if (abs(d) < PRECISION) break;\n"
    "    }\n"
    "\n"
    "    highp vec3 p;\n"
    "    p.xy = vec2(2.0 * SQRT2 / PI * lambda * cos(theta), SQRT2 * sin(theta));\n"
    "    p.z = -1.0;\n"
    "    p *= dist;\n"
    "    vec4 ret = u_proj_mat * vec4(p, 1.0);\n"
    "    ret.z = 0.0;\n"
    "    ret.w = 1.0;\n"
    "    return ret;\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\projections_glsl, "shaders\projections.glsl", DATA_shaders\projections_glsl, false)

