// Auto generated from tools/makeassets.py

static const unsigned char DATA_shaders\texture_2d_glsl[1262] __attribute__((aligned(4))) =
    "/* Stellarium Web Engine - Copyright (c) 2022 - Stellarium Labs SRL\n"
    " *\n"
    " * This program is licensed under the terms of the GNU AGPL v3, or\n"
    " * alternatively under a commercial licence.\n"
    " *\n"
    " * The terms of the AGPL v3 license can be found in the main directory of this\n"
    " * repository.\n"
    " */\n"
    "\n"
    "uniform mediump vec4        u_color;\n"
    "uniform mediump sampler2D   u_tex;\n"
    "uniform lowp    vec2        u_win_size;\n"
    "\n"
    "varying highp   vec2        v_tex_pos;\n"
    "\n"
    "#ifdef VERTEX_SHADER\n"
    "\n"
    "#ifdef HAS_VIEW_POS\n"
    "    attribute highp vec3 a_pos;\n"
    "    #includes \"projections.glsl\"\n"
    "#endif\n"
    "\n"
    "attribute highp     vec2    a_wpos;\n"
    "attribute mediump   vec2    a_tex_pos;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    #ifdef HAS_VIEW_POS\n"
    "        gl_Position = proj(a_pos);\n"
    "    #else\n"
    "        gl_Position = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "    #endif\n"
    "    gl_Position.xy = (a_wpos / u_win_size - 0.5) * vec2(2.0, -2.0);\n"
    "    gl_Position.xy *= gl_Position.w;\n"
    "    v_tex_pos = a_tex_pos;\n"
    "}\n"
    "\n"
    "#endif\n"
    "#ifdef FRAGMENT_SHADER\n"
    "\n"
    "void main()\n"
    "{\n"
    "#ifndef TEXTURE_LUMINANCE\n"
    "    gl_FragColor = texture2D(u_tex, v_tex_pos) * u_color;\n"
    "#else\n"
    "    // Luminance mode: the texture only applies to the alpha channel.\n"
    "    gl_FragColor = u_color;\n"
    "    gl_FragColor.a *= texture2D(u_tex, v_tex_pos).r;\n"
    "#endif\n"
    "}\n"
    "\n"
    "#endif\n"
    "";

ASSET_REGISTER(shaders\texture_2d_glsl, "shaders\texture_2d.glsl", DATA_shaders\texture_2d_glsl, false)

